#!/bin/bash
#                rad gap
python make2d.py 100 10 1
python make2d.py 100 20 2
python make2d.py 100 30 3
python make2d.py 100 40 4
python make2d.py 100 50 5
python make2d.py 100 60 6
python make2d.py 100 70 7
python make2d.py 100 80 8
python make2d.py 100 90 9
python make2d.py 100 100 10






